### ISSUE TITLE
Native type must not be used as object. 

### ISSUE THREAD

**Issue by akar1n** [hammer-tools/php-hammer#12]
I pass the class name to the function and access a constant of this class by referring to it through a string. I receive an error message from php-hammer stating "native type must not be used as object.", but this is a static call, not an object. Is this the expected behavior?

**Comment by rentalhost** [comment]
Can you provide a complete example?

**Comment by akar1n** [comment]
Class Bar contains a public constant CONST. 
![изображение](https://user-images.githubusercontent.com/8540368/225497065-c97199a2-13a2-4da8-9fa6-dd4991b6a911.png)
Is that enough for an example?

**Comment by rentalhost** [comment]
Perfect! I believe that in the case you mentioned I can try to check if the type of the parameter is a `class-string` and allow its use in this way. Thanks!

**Comment by rentalhost** [comment]
**Implemented in version 0.22.0:**

Hello @akar1n, the new **version 0.22.0** has just been released and is available for direct download from the **[Releases](https://github.com/hammer-tools/php-hammer/releases/tag/0.22.0)** page. This update will be available on the **[Jetbrains Market](https://plugins.jetbrains.com/plugin/19515-php-hammer)** in approximately three days if you prefer to wait.

**This version comes with some new features, now totaling 51 inspections:**

- Support for the **new PhpStorm 2023.2 EAP** (_minimum version from now on_);
- Inspection to suggest strict comparison when possible;
- Inspection to suggest the use of non-deprecated functions (e.g., `mt_rand()` to `random_int()`);
- Additional feature: add missing _semicolon_ when saving a PHP file;
- Other minor improvements.

Regarding your report, this issue has also been fixed in this version. Now, variables typed as `class-string` will be ignored by this inspection.
