### ISSUE TITLE
Livewire/Alpine @entangle property shows inspection "debug function usage"

### ISSUE THREAD

**Issue by andrewdwallo** [hammer-tools/php-hammer#13]
I'm not sure if PhpStorm is causing it or your plugin but hovering over "@entangle('property')" directive shows it as a "print_r" function. In which case, you may be adding the inspection based on PHPStorm's evaluation.

**Comment by rentalhost** [comment]
**Implemented in version 0.22.0:**

Hello @akar1n, the new **version 0.22.0** has just been released and is available for direct download from the **[Releases](https://github.com/hammer-tools/php-hammer/releases/tag/0.22.0)** page. This update will be available on the **[Jetbrains Market](https://plugins.jetbrains.com/plugin/19515-php-hammer)** in approximately three days if you prefer to wait.

**This version comes with some new features, now totaling 51 inspections:**

- Support for the **new PhpStorm 2023.2 EAP** (_minimum version from now on_);
- Inspection to suggest strict comparison when possible;
- Inspection to suggest the use of non-deprecated functions (e.g., `mt_rand()` to `random_int()`);
- Additional feature: add missing _semicolon_ when saving a PHP file;
- Other minor improvements.

Regarding your report, this issue has also been fixed in this version. Since the support for interaction between PHP and Blade is quite limited (in this particular case, it is not possible to determine that `print_r()` is called from within a Blade directive), the only solution in this case is to partially disable this inspection (by ignoring the usage of `print_r()` within Blade files).

**Comment by andrewdwallo** [comment]
Okay sounds good, thanks!
