### ISSUE TITLE
Make narrow sidebar more readable/useable

### ISSUE THREAD

**Issue by reedy** [hammer-tools/php-hammer#27]
I'm guessing min width or similar is being set on the buttons and text.

It feels like at least up to some (currently smaller than it is currently) size, the buttons could actually shrink and still show the text etc

![Screenshot 2023-08-26 at 19 43 48](https://github.com/hammer-tools/php-hammer/assets/67615/74a2a91e-69b1-45ce-a54b-cebdb02ab3a2)
![Screenshot 2023-08-26 at 19 42 58](https://github.com/hammer-tools/php-hammer/assets/67615/83abd277-f692-426e-807c-5eed44eb885a)

Compared with the notifications sidebar:

![Screenshot 2023-08-26 at 19 47 24](https://github.com/hammer-tools/php-hammer/assets/67615/89fc7286-9c06-403c-95af-3c549d4e893b)
![Screenshot 2023-08-26 at 19 47 32](https://github.com/hammer-tools/php-hammer/assets/67615/d27fb482-451b-4e24-b2e1-1d78a811a309)
![Screenshot 2023-08-26 at 19 47 36](https://github.com/hammer-tools/php-hammer/assets/67615/89e6c43f-1d93-4d47-a538-590c883e9f21)

**Comment by rentalhost** [comment]
Thank you for taking the time to report this issue. The fix has been implemented in version **0.24.0** and is available on the **[Releases](https://github.com/hammer-tools/php-hammer/releases)** page for manual installation. Alternatively, you can wait for the official release on the **JetBrains Marketplace**, which should happen in approximately 3 days.

- **In response to the issue you raised:** I managed to understand what you meant and simulate the problem. I made some minor adjustments to ensure that the texts don't force a minimum size. Additionally, I removed the checkbox for the "_add missing semicolon_" feature because it was causing too many issues (and at the same time, the checkbox itself was causing problems with the minimum width of this box you mentioned).
