### ISSUE TITLE
Inspection can't use native type as object does not work with multiple types

### ISSUE THREAD

**Issue by brazenvoid** [hammer-tools/php-hammer#38]
The title is indicative enough, explanation being, a declaration like: `Model|int $payable`, does not validate the inspection. Instead it keeps on detecting it as an error as `int` is a possible type. 

Then there are obviously cases with combination types like DNF in current v8.2.

**Comment by rentalhost** [comment]
@brazenvoid Thanks for you report. Can you please give a sample code? I have tried with the following, but it is working as expected:

```php
class Example
{
    public function test(self|int $abc)
    {
        return $abc->test(123);
        // $abc: "PHP Hammer: native type must not be used as object."
    }
}
```

If my code makes sense to you, and you think it shouldn't report a problem, I can explain: this inspection checks whether one of the defined types for `$abc` is a primitive type (like `int` in this case). So, calling `$abc->test()` with an argument like `123` would result in an error because the type hasn't been tested properly. To resolve this, it would be ideal to use type narrowing, like the following code:

```php
class Example
{
    public function test(self|int $abc)
    {
        if ($abc instanceof self) {
            return $abc->test(123);
        }

        return $abc * 2;
    }
}
```

On the other hand, PHPStorm's type narrowing is a bit suboptimal, and in `$abc * 2`, it will still "see" the type as `Example|int` for `$abc`, instead of just `int` as expected. However, the inspection won't return any errors anymore.

But if I misunderstood, I would appreciate a better explanation that could help me understand. Sometimes, due to the language barrier, I have difficulty comprehending. A code example would be quite useful here.

**Comment by brazenvoid** [comment]
You are right and I am doing type narrowing too. But the inspection always marks the instance after the narrowing as wrong. This is not a new thing, I just chose to always keep it disabled. Just because of #10 I keep having to disable it, haha. 

I think the difference is that I am not working with "self" which is a native type though still referencing an object but an explicit Class reference (not the class the function is in). 

I can't get an example after a quick search. If I come across it again I'll attach it here.

**Comment by rentalhost** [comment]
@brazenvoid But it's just as I said: PhpStorm's type narrowing fails in these cases. So, if we reverse the example I gave, even if we perform type narrowing correctly (on our side), PhpStorm doesn't handle the job properly and will generate a false positive in php-hammer:

```php
class Example
{
    public function test(Example|int $abc)
    {
        if (gettype($abc) === 'integer') {
            return $abc * 123;
        }

        // Even with the type narrowing above, we'll have an error here:
        // $abc => PHP Hammer: native type must not be used as an object.
        $abc->test(123);

        if (is_int($abc)) {
            return $abc * 123;
        }

        // However, type narrowing using is_int() will work correctly.
        // Even though $abc is "seen" (CTRL+hover) as Example|int, instead of just int.
        $abc->test(123);
    }
}
```

I will close this report for now. However, as soon as you come across an example that helps me better understand your case, I'll be happy to investigate and try to find the best solution.

**Comment by Samuell1** [comment]
Hey, looks like i got same issue defining relation in OctoberCMS like this:

```
    public function updateFunction(): void
    {
        $product = $this->variant;
        
            if ($product->quantity) { // here it errors out on it
               // code
            }
    }
```
