### ISSUE TITLE
Feature request: \assert() inspections

### ISSUE THREAD

**Issue by asgraf** [hammer-tools/php-hammer#43]
This inspection should detect asserts with conditions that will be always true or always false based on static analysis

```php
ini_set('assert.exception', 1);//0 - warning when assert fails, 1 - exception when assert fails

$x = 5;
\assert(is_int($x));//useless - always true
\assert($x === 5);//useless - always true
\assert($x !== 5);//invalid - always false

function someFunction(int $a, int $b)
{
    \assert($a < $b);
    \assert($a > $b);// invalid - always false because of previous assert
    \assert($a <= $b);//useless - always true because of first assert
    \assert($a === $b);// invalid - always false because of first assert
}


class Entity implements EntityInterface {}
class User extends Entity implements IdentityInterface {}
class NonUser extends Entity {}

function someFunction2(Entity $entity)
{
    \assert($entity!== null);//useless - always true
    \assert(is_object($entity));//useless - always true
    \assert($entity instanceof EntityInterface);//useless - always true
    \assert($entity instanceof IdentityInterface);
    \assert($entity instanceof Entity);//useless - always true
    \assert($entity instanceof User);
    \assert($entity instanceof NonUser);//invalid - always false because incompatible with previous assert
}

function someFunction3(User $user)
{
    \assert($entity instanceof NonUser);//invalid - always false
    \assert($user!== null);//useless - always true
    \assert(is_object($user));//useless - always true
    \assert($user instanceof EntityInterface);//useless - always true
    \assert($user instanceof IdentityInterface);//useless - always true
    \assert($user instanceof Entity);//useless - always true
    \assert($user instanceof User);//useless - always true
}

function someFunction4(IdentityInterface $identity)
{
    \assert($entity instanceof NonUser);//invalid - always false (NonUser does not implement IdentityInterface)
    \assert(is_object($identity ));
    \assert($identity instanceof EntityInterface);
    \assert($identity instanceof IdentityInterface);//useless - always true
    \assert($identity instanceof Entity);
    \assert($identity instanceof User);
}

function someFunction5(?User $var)
{
    \assert($var !== null);//$var instanceof User can be assumed
    \assert(is_object($var));//useless - always true because of previous assert
    \assert($var instanceof EntityInterface);//useless - always true because of first assert
    \assert($var instanceof IdentityInterface);//useless - always true because of first assert
    \assert($var instanceof Entity);//useless - always true because of first assert
    \assert($var instanceof User);//useless - always true because of first assert
}

function someFunction5(?Entity $var)
{
    \assert($var instanceof Entity || $var === null)//useless - always true
    \assert($var instanceof NonUser || $var === null)
    \assert($var !== null);//$var instanceof NonUser can be assumed
    \assert(is_object($var));//useless - always true because of previous assert
    \assert($var instanceof EntityInterface);//useless - always true because NonUser implements EntityInterface
    \assert($var instanceof IdentityInterface);//invalid - always false because NonUser  does not implement IdentityInterface
    \assert($var instanceof Entity);//useless - always true because NonUser extends Entity
    \assert($var instanceof User);//invalid - always false because NonUser is not a User
}
```

**Comment by rentalhost** [comment]
Let's break down each point:

```php
$x = 5;

\assert(is_int($x)); // useless - always true
```

- I agree with this point. Since PhpStorm identifies `$x` specifically as an `int`, there's no room for error. PhpStorm seems to lack validation for this case.

```php
\assert($x === 5); // useless - always true
\assert($x !== 5); // invalid - always false
```

- I understand your concern here. It's indeed quite challenging to maintain a line-by-line "machine state" and detect even simple value changes. The major challenge is ensuring that PhpStorm updates this state in real-time and doesn't risk removing something necessary. PhpStorm has an inspection for this, but it only works within a closed scope (as we'll see below).

```php
function someFunction(int $a, int $b)
{
    \assert($a < $b);
    \assert($a > $b); // invalid - always false because of the previous assert
    \assert($a <= $b); // useless - always true because of the first assert
    \assert($a === $b); // invalid - always false because of the first assert
}
```

- The challenge here is similar. However, PhpStorm seems to work well in this case through the "Condition always evaluates to 'true/false'" inspection (which also addresses the previous case, as mentioned, as long as it's within a closed scope).

```php
function someFunction3(User $user)
{
    \assert($entity instanceof NonUser); // invalid - always false
    \assert($user !== null); // useless - always true
    \assert(is_object($user)); // useless - always true
    \assert($user instanceof EntityInterface); // useless - always true
    \assert($user instanceof IdentityInterface); // useless - always true
    \assert($user instanceof Entity); // useless - always true
    \assert($user instanceof User); // useless - always true
}
```

- If you meant to write `$entity` instead of `$user`, PhpStorm will identify that the variable doesn't exist, which is a useful error. If it's a typo and you meant `$user`, PhpStorm should be able to identify an "always false" error.

- In the second case, it would be a viable validation since it indeed cannot be `null` here, and PhpStorm doesn't validate this. The same applies to `is_object()` and the other `instanceof` checks (which I expected PhpStorm to validate).

- The same comments apply to `someFunction4` and `someFunction5`.

```php
function someFunction5(?User $var)
{
    \assert($var !== null); // $var instanceof User can be assumed
   // ...
}
```

- In this case, it might be more beneficial to use `instanceof` instead of the way it's currently written, as it would be clearer and could potentially assist in better type narrowing.

```php
function someFunction6(?Entity $var)
{
    assert($var instanceof Entity || $var === null); //useless - always true
    // ...
}
```

- I agree, this is a valid case. However, as you pointed out, in more complex scenarios with multiple comparisons, including `||` and `&&`, it might render this function impractical.

Overall, it's important to strike a balance between making the code more concise and ensuring that it remains clear and maintainable, especially in complex situations. PhpStorm's inspections are valuable aids in achieving this balance.

I agree with your proposed ideas for improving the inspections in PhpStorm:

1. Informing situations where exclusive type declarations like `$x = 5` are always true when used with corresponding exclusive checkers like `is_int()` (e.g., `float` for `is_float()`, `string` for `is_string()`, `object` for `is_object`, etc.).

2. Informing situations where exclusive type declarations like `User $x` are unnecessarily tested with `is_object()` or against `null`.

These improvements would make PhpStorm even more efficient in identifying and alerting developers about code that can be further optimized or clarified, while still maintaining code readability. However, more complex scenarios, especially those involving type narrowing based on previous conditions or within conditionals, would indeed require direct collaboration with the JetBrains IntelliJ team to ensure the best possible type narrowing capabilities.
