### ISSUE TITLE
Feature request: replace exploitable extract() with array unpacking inspection

### ISSUE THREAD

**Issue by asgraf** [hammer-tools/php-hammer#47]
Consider this purposefully exploitable code :

```php
$isLoggedIn = false;
extract($postData);// code author assumed only 'login' and 'password' fields are in $postData
if(checkPasword($login, $password)) {
    $isLoggedIn = true;
}
var_dump($isLoggedIn);
```
In this example author assumed `$postData` with content like `['login' => 'aaa', 'password' => 'bbb']`
but this `extract()` can be easily exploited by posting `['login' => 'aaa', 'password' => 'bbb', 'isLoggedIn' => true]` instead

Same code but without exploit:
```php
$isLoggedIn = false;
['login' => $login, 'password' => $password] = $postData; //$isLoggedIn cannot be overridden anymore
if(checkPasword($login, $password)) {
    $isLoggedIn = true;
}
var_dump($isLoggedIn);
```

So my suggestion is inspection that report all usages of `extract()` as a potential security vulnerability (code error) and optionally suggest array unpacking as an quick fix.

**Comment by asgraf** [comment]
On older PHP versions (that does not support array unpacking) display error only

**Comment by rentalhost** [comment]
In general, I find it unfeasible to suggest a problem, and the fix itself doesn't seem all that interesting. Perhaps in the vast majority of cases, the user just wants to do an `EXTR_SKIP` because it's highly unlikely that they're extracting data from user input (although not impossible).

So my suggestion here would be to specifically suggest setting the second parameter as `EXTR_SKIP`, and if the user truly intends to perform an overwrite, they can either explicitly specify it using `EXTR_OVERWRITE` or follow your recommendation.

It might even be interesting to always report an error when using `EXTR_OVERWRITE`, even if it's manually typed, but the issue is that it would require using `@noinspection`, which could clutter the code. So there's not much to be done here (or maybe make it an option disabled by default). This would ensure that the user is intentionally using `EXTR_OVERWRITE`.

**Comment by asgraf** [comment]
Maybe this is personal preference but I consider code with array unpacking more readable than one with `extract()`
All unpacked variables are clearly listed.

**Comment by rentalhost** [comment]
When you have full control over what will be `extract()`'ed, your solution is indeed ideal. In this case, I don't see much sense in using `extract()` when you have total control - you could even use `$postData['login']` directly if it's a one-time use or store to a variable directly.

The problem arises when you don't have control and are [**forced**](https://github.com/laravel/framework/blob/0aeececbde74888cfc24839961dd8c49452eb05f/src/Illuminate/Console/View/Components/Component.php#L64) to use `extract()`.

To me, the only mistake PHP made was making `EXTR_OVERWRITE` the default instead of `EXTR_SKIP`. Perhaps it's something we can suggest to PHP to make `EXTR_SKIP` the default in PHP 10 (and treat `EXTR_OVERWRITE` as 'default deprecated' or something of the sort in PHP 9).

Indeed, as suggested above, I can create an inspection that recommends using `EXTR_SKIP` to ensure safer code for both your codebase and general users. I can also create an option (disabled by default to avoid clutter) that notifies the use of `EXTR_OVERWRITE`, forcing the user either:

- To replace it with the format you suggested (which you can include as an example in the inspection description); or 
- To use `EXTR_OVERWRITE` explicitly;
- To use `@noinspection` explicitly (making sure they are aware of what they're doing);
- Or it can accept the use of `extract(any_function())`, so we can just accept as "fine" because we can did something like (_option-aware?_):

```php
extract(array_intersect_key($array, array_flip(['login', 'password'])))
```

In general terms, if we use a function, the inspection can assume that it has already been sanitized or that it truly returns something precise (which can still be an error, such as `extract(Request::all())`). Or perhaps consider only the pattern I specified above (`array_intersect_key()` + `array_flip()`), as it is safe and similar to your code, but also clutter.

**In the end, I believe the best options are:**

- **For inspection:** require the second parameter to be defined, even if it's `EXTR_OVERWRITE` redundantly (_option-aware?_ enabled by default?).
- **For the quick-fix:** suggest using `EXTR_SKIP`, announcing that there may be a change in behavior.
