### ISSUE TITLE
Incompatible with PHPStorm 2024.3

### ISSUE THREAD

**Issue by francislavoie** [hammer-tools/php-hammer#66]
> Incompatible: requires IDE build 242.* or earlier

Would it make sense to change the version constraint to allow newer versions optimistically? Seems annoying to have to update it every time the IDE updates.

**Comment by rentalhost** [comment]
I am unsure if this is permitted by the JetBrains Plugin Manager, but it might be worth trying.

**Comment by francislavoie** [comment]
The other option is uploading new versions compat with the next one when it hits EAP instead of on final release, then it would be ready ahead of time.

**Comment by francislavoie** [comment]
For sake of argument, I looked at some other plugins I have, this one does not specify an "until" version:

https://github.com/klesun/deep-assoc-completion/blob/274b5054ab65ecd23d51d1ab405c646d2988c589/resources/META-INF/plugin.xml#L57

So I think you could just remove `until-build="242.*"` and it should work indefinitely.

**Comment by andrewdwallo** [comment]
Is this plugin not active anymore?

**Comment by rentalhost** [comment]
Let's say it's _slowly active_ because I need an IDEA Ultimate license to update it, and JetBrains usually grants me one. However, I need to reach out and set aside some time to handle this. Unfortunately, I haven't yet figured out a way to fully automate this process, and last time, a few people collaborated on the update.

**Comment by andrewdwallo** [comment]
@rentalhost Is there something that can be done for this to be compatible with 2024.3? Do you need help or something? I really like this plugin but as PHPStorm keeps making new releases, I'm really considering moving away from this plugin.

**Comment by rentalhost** [comment]
@andrewdwallo Unfortunately, to maintain the plugin, I need an active IDEA Ultimate account, as well as some time to update the code based on the new features in the current PhpStorm version, which is quite time-consuming. If someone is willing to take over from here, it would be possible to keep the plugin updated for future versions. Part of the issue is also my own, as I’ve been moving away from PHP to another language. However, I would still like to at least keep it active, as I’m not the only one using it.

**Comment by andrewdwallo** [comment]
Man that reallly sucks..

**Comment by tlamy** [comment]
@rentalhost Though my Java knowledge isn't the best by far, I'm die hard PHP and hereby offer my help. 

@andrewdwallo After the recent changes to the build system it's pretty straightforward to build the plugin now; I used the free Intellij Community Edition to do so when PS was in 2024.3 EAP.

**Comment by rentalhost** [comment]
**Good news!** I was able to easily rebuild for the new version. So, I’ll be releasing a new version here and on the Marketplace within the next 4 hours. However, I’ll take this opportunity to update all dependencies to prevent any issues with future updates.

**Comment by francislavoie** [comment]
Thank you!

**Comment by rentalhost** [comment]
I wasn’t able to update the dependencies for now, but it was possible to compile with the current ones. I’ll submit it to the Marketplace, but you can [**download it directly from here**](https://github.com/hammer-tools/php-hammer/releases) while waiting for JetBrains' approval.

**Comment by andrewdwallo** [comment]
Awesome!

**Comment by francislavoie** [comment]
It's approved! I got the update through normal channels! Thank you.
